<a href="https://colab.research.google.com/github/DickyDescta/Python-project/blob/main/Pertemuan_3_DAA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
aList = ["john", 33,"Toronto", True]
print(aList)

['john', 33, 'Toronto', True]


In [26]:
import datetime as dt
tanggal = dt.date.today()
mahasiswa = ["Dicky Descta","2023071033","Prodi Informatika","DAA",tanggal,"Universitas Pembangunan Jaya"]
print(mahasiswa)

['Dicky Descta', '2023071033', 'Prodi Informatika', 'DAA', datetime.date(2024, 9, 19), 'Universitas Pembangunan Jaya']


In [27]:
print ("NIM", mahasiswa[1:2])
print ("NIM", mahasiswa[2:3])
print ("NIM", mahasiswa[0:6])

NIM ['2023071033']
NIM ['Prodi Informatika']
NIM ['Dicky Descta', '2023071033', 'Prodi Informatika', 'DAA', datetime.date(2024, 9, 19), 'Universitas Pembangunan Jaya']


In [9]:
print (mahasiswa[1])
print (mahasiswa[5])

2023071033
universitas pembangunan Jaya


In [28]:
for aMahasiswa in mahasiswa:
    print ("UPJ", aMahasiswa)

UPJ Dicky Descta
UPJ 2023071033
UPJ Prodi Informatika
UPJ DAA
UPJ 2024-09-19
UPJ Universitas Pembangunan Jaya


In [31]:
bin_colors=["Red","Green","Blue","Yellow"]
bin_colors[1:4]

['Green', 'Blue', 'Yellow']

In [33]:
UPJ=("universitas","Pembangunan","Jaya")
UPJ[0:3]

('universitas', 'Pembangunan', 'Jaya')

In [34]:
NESTED_TUPLE = (100,(200,400,600),300,(400,800))
NESTED_TUPLE

(100, (200, 400, 600), 300, (400, 800))

In [35]:
UPJ ={
    "Nama": "Dicky Descta",
    "NIM": "2023071033",
    "Prodi": "Informatika",
    "Universitas": "Universitas Pembangunan Jaya"
}
print(UPJ)

{'Nama': 'Dicky Descta', 'NIM': '2023071033', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


In [51]:

yellow_set = {'dandelions', 'leaves', 'fire hydrant'}
red_set = {'blood', 'rose', 'fire hydrant','leaves'}

yellow_and_red = yellow_set.intersection(red_set)

yellow_only = yellow_set - yellow_and_red
red_only = red_set - yellow_and_red

yellow_or_red = yellow_only.union(red_only, yellow_and_red)

print("yellow/red:", yellow_or_red)
print("yellow&red:", yellow_and_red)

yellow/red: {'dandelions', 'leaves', 'fire hydrant', 'blood', 'rose'}
yellow&red: {'leaves', 'fire hydrant'}


In [49]:
import pandas as pd

df = pd.DataFrame([
    [1, 'Informatika', 50, 30,20],
    [2, 'Sistem informasi', 55,30,25],
    [3, 'Teknik Sipil', 40,30,10]],
    columns=['No', 'Prodi', 'Mahasiswa','LakiLaki','Perempuan'])

print(df)

from IPython.display import display
display(df)


   No             Prodi  Mahasiswa  LakiLaki  Perempuan
0   1       Informatika         50        30         20
1   2  Sistem informasi         55        30         25
2   3      Teknik Sipil         40        30         10


No             Prodi  Mahasiswa  LakiLaki  Perempuan
0   1       Informatika         50        30         20
1   2  Sistem informasi         55        30         25
2   3      Teknik Sipil         40        30         10

In [53]:
import numpy as np
myMatrix = np.array([[100,200,300],[700,600,500],[900,1000,800]])
print(myMatrix)

transpose_matrix = myMatrix.transpose()
print(transpose_matrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
